---
- name: Deploy ingress namespace
  local_action:
    module: k8s
    state: "{{ ingress_nginx_resource_state }}"
    kubeconfig: "{{ ingress_nginx_resource_kubeconfig }}"
    definition: "{{ lookup('template', 'namespace.yml.j2') }}"

- name: Deploy ingress ConfigMaps
  local_action:
    module: k8s
    state: "{{ ingress_nginx_resource_state }}"
    kubeconfig: "{{ ingress_nginx_resource_kubeconfig }}"
    definition: "{{ lookup('template', item) }}"
  with_items:
    - 'configmaps/nginx-configuration.yml.j2'

- name: Deploy ingress RBAC
  local_action:
    module: k8s
    state: "{{ ingress_nginx_resource_state }}"
    kubeconfig: "{{ ingress_nginx_resource_kubeconfig }}"
    definition: "{{ lookup('template', item) }}"
  with_items:
    - 'rbac/clusterrole.yml.j2'
    - 'rbac/clusterrolebinding.yml.j2'
    - 'rbac/role.yml.j2'
    - 'rbac/rolebinding.yml.j2'
    - 'rbac/serviceaccount.yml.j2'

- name: Deploy ingress Service
  local_action:
    module: k8s
    state: "{{ ingress_nginx_resource_state }}"
    kubeconfig: "{{ ingress_nginx_resource_kubeconfig }}"
    definition: "{{ lookup('template', 'service.yml.j2') }}"

- name: Deploy ingress DaemonSet
  local_action:
    module: k8s
    state: "{{ ingress_nginx_resource_state }}"
    kubeconfig: "{{ ingress_nginx_resource_kubeconfig }}"
    definition: "{{ lookup('template', 'daemon-set.yml.j2') }}"
